### ISSUE TITLE
full horizontal row support (missing 2 keys only)

### ISSUE THREAD

**Issue by G2G2G2G** [UltimateHackingKeyboard/keycluster-electronics#1]
My left hand uses next tier of keys in qwerty.. (because the right hand is mostly on the mouse, my highly evolved left hand has learned more of the keyboard)
Y
H
N
You currently have the "6" key which is part of this layer, but cut it off at T, G and B.. 
Currently the only left hand module adds 3 keys, I am thinking what if you were to add more modular keys for people like me?
Something like:
![keys](https://user-images.githubusercontent.com/50514477/147698321-69a10545-e466-42a6-9dc4-1cb94d72789b.jpg)
adding the key in the "7" place isn't fully necessary, but H and Y are

Thanks
(sorry if wrong section, this seemed to be the most applicable)

**Comment by mondalaci** [comment]
Hi there! We don't plan to make such a module, but we'll release a development kit, so non-official modules, such as the one you're suggesting, will be possible to be made.
